# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - master # déclenche seulement sur la branche master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v5

      # 2. Setup Node
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Run tests
      - name: Test project
        run: npm test

      # 5. Lint project
      - name: Lint project
        run: npm run lint

      # 6. Charger l’historique des rapports depuis gh-pages
      - name: Load test report history
        uses: actions/checkout@v5
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: allure-history

      # 7. Générer le rapport Allure
      - name: Build Allure report
        uses: allure-framework/allure-report-action@v2
        if: always()
        with:
          allure_results: build/allure-results
          allure_history: allure-history
          keep_history: true

      # 8. Publier sur GitHub Pages
      - name: Publish Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
